### PR TITLE
Fixed a syntax error in RNMailModule.

### PR DESCRIPTION
**Pull request by timscott**
Removed extra bracket at the end of RNMailModule.

### CODE REVIEW

**Review by adamski — APPROVED** [review]
Thanks!

**Comment by timscott** [comment]
After fixing this, it's still not working for me on Android. Not just not attachments, it's pulling up an empty email -- no subject, body, recipients, etc., even if I don't specify any attachments. iOS is working as expected.

**Comment by adamski** [comment]
OK, did you use the altered syntax for attachments, e.g.
```js
    attachments: [{
        path: this.imageFilePath,  // The absolute path of the file from which to read data.
        type: 'png',   // Mime Type: jpg, png, doc, ppt, html, pdf
      },{
        path: this.audioFilePath,
        type: 'wav',   
      }]
```

Can you step through with a debugger, or put in some log statements to check values are getting through OK?

Is the [main repo](https://github.com/chirag04/react-native-mail) working for you? 

I've not tested this on Android yet.

**Comment by timscott** [comment]
@adamski 

I am using the main package, but I have yet to try the singular attachment ability. I was going to do that next.

In the multi-attachment version, I am debugging the Java code, and  this is the value of `options.getArray("attachments");` (with redactions):

```js
[{
  "type": "pdf",
  "name": "file1.pdf",
  "path": "/data/data/com.redacted.debug/files/file1.pdf"
}, {
  "type": "pdf",
  "name": "file2.pdf",
  "path": "/data/data/com.redacted.debug/files/file2.pdf"
}]
```

The value of `uris` passed into `i.putParcelableArrayListExtra` is:

```
file:///data/data/com.redacted.debug/files/file1.pdf
file:///data/data/com.redacted.debug/files/file2.pdf
```

One thing I notice is that these two blocks are almost duplicate, and both call `i.putParcelableArrayListExtra(Intent.EXTRA_STREAM, uris);` at the end. This seems likely to be wrong, but I don't know whether it's causing any actual problems.

https://github.com/timscott/react-native-mail/blob/e85c5265c659c18dd80625f428f88ffc26230ad3/android/src/main/java/com/chirag/RNMail/RNMailModule.java#L83-L97

https://github.com/timscott/react-native-mail/blob/e85c5265c659c18dd80625f428f88ffc26230ad3/android/src/main/java/com/chirag/RNMail/RNMailModule.java#L104-L119

The biggest issue for me is that not only is the attachment feature not working, it's just opening empty emails. This means that I cannot use this version at all even I could live with not supporting attachments for Android.

Thanks for any help!

**Comment by timscott** [comment]
Also, I notice that this condition is true, so the files do exist I guess:

https://github.com/timscott/react-native-mail/blob/e85c5265c659c18dd80625f428f88ffc26230ad3/android/src/main/java/com/chirag/RNMail/RNMailModule.java#L113

**Comment by timscott** [comment]
When I remove this code, the other fields populate, but not the attachments:

https://github.com/timscott/react-native-mail/blob/e85c5265c659c18dd80625f428f88ffc26230ad3/android/src/main/java/com/chirag/RNMail/RNMailModule.java#L121-L125

**Comment by timscott** [comment]
I think I solved it. Look for another PR shortly. Seems to have to do with this: https://stackoverflow.com/a/15022268/29493

**Pull request merged**
